setwd("~/oec/cran")
library(devtools)
library(roxygen2)
library(knitr)
document()
system("R CMD Rd2pdf ~/oec/cran/")
file.rename("~/oec/cran/cran.pdf", "~/oec/cran/oec.pdf")
file.remove("~/oec/gh-pages/oec.pdf")
file.copy("~/oec/cran/oec.pdf", "~/oec/gh-pages/")
file.remove("~/oec/cran/oec.pdf")
file.remove("~/oec/gh-pages/README.md")
file.copy("~/oec/README.md", "~/oec/gh-pages/README.md")
#check()
