setwd("/Users/pacha/oec")
library(devtools)
library(roxygen2)
library(knitr)
document()
system("R CMD Rd2pdf /Users/pacha/oec")
file.remove("gh-pages/d3plus.pdf")
file.copy("oec.pdf", "gh-pages/oec")
file.remove("oec.pdf")
file.remove("gh-pages/README.md")
file.copy("README.md", "gh-pages/README.md")
#check()
