setwd("/Users/pacha/oec/cran")
library(devtools)
library(roxygen2)
library(knitr)
document()
system("R CMD Rd2pdf /Users/pacha/oec/cran/")
file.rename("/Users/pacha/oec/cran/cran.pdf", "/Users/pacha/oec/cran/oec.pdf")
file.remove("/Users/pacha/oec/gh-pages/oec.pdf")
file.copy("/Users/pacha/oec/cran/oec.pdf", "/Users/pacha/oec/gh-pages/")
file.remove("/Users/pacha/oec/cran/oec.pdf")
file.remove("/Users/pacha/oec/gh-pages/README.md")
file.copy("/Users/pacha/oec/README.md", "/Users/pacha/oec/gh-pages/README.md")
#check()
