---
title: "OEC Data"
author: "Pachá 帕夏 "
date: "Updated `r Sys.Date()`"
output:
 prettydoc::html_pretty:
  theme: datawheel
  highlight: github
  self_contained: no
  includes:
   after_body: footer.html
---

# Welcome

Here we use the *Tidy Data* principles exposed by Hadley Wickham in the [Journal of Statistical Software](https://www.jstatsoft.org/article/view/v059i10).

If you have questions send me an email to *mvargassepulveda [at] gmail.com*



# Sections

[Clean data](#clean_data)

* [UN COMTRADE](#clean_data_un_comtrade)
<!--
    * [HS 92](#clean_data_un_comtrade_hs92)
    * [SITC (rev.2)](#clean_data_un_comtrade_sitc_rev2)
-->

[Raw data](#raw_data)

* [UN COMTRADE](#raw_data_un_comtrade)
<!--
    * [HS 92](#raw_data_un_comtrade_hs92)
    * [SITC (rev. 2)](#raw_data_un_comtrade_sitc_rev2)
    * [SITC (rev. 1)](#raw_data_un_comtrade_sitc_rev1)
-->
* [CEPII](#raw_data_cepii)
<!--
    * [Geo](#raw_data_cepii_geo)
    * [Gravity](#raw_data_cepii_gravity)
-->

[Documentation](#documentation)
<!--
    * [CEPII](#documentation_cepii)
-->

[Scripts](#scripts)
<!--
    * [UN COMTRADE](#scripts_un_comtrade)
        * [HS92](#scripts_un_comtrade_hs92)
        * [SITC (rev. 2)](#scripts_un_comtrade_sitc_rev2)
        * [SITC (rev. 1)](#scripts_un_comtrade_sitc_rev1)
    * [CEPII](#scripts_cepii)
-->    



<div id="clean_data">
# Clean data

<div id="clean_data_un_comtrade">
## UN COMTRADE

The difference between this and the raw data is that here we reorganized the information providing an `exports_fob_usd` column (in FOB dollars) and an `imports_cif_usd` column (in CIF dollars) instead of a `Trade Flow` column with labels "Imports" and "Exports" and a `Trade Value (US$)` column that contains both FOB and CIF dollars. Also we provide a column `marker` with labels as follow:

* 1 = The reported values are ok ($CIF/FOB > 1$) 
* 2 = The reported values had to be replaced with counter reported values ($CIF/FOB = 1$)
* 3 = The reported values are incomplete ($CIF/FOB < 1$)
* NA = No data available

In the case of missing data we checked counter reported numbers, so that in the cases that country $i$ reported 0 or null exports of product $p$ to country $j$ we replaced those values with what country $j$ reported as imports of product $p$ from country $i$ when it was possible.

<div id="clean_data_un_comtrade_hs92">
### HS92 clean data

#### CSV

<div id="threecolumns">
<li>[HS 2015](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_2015_clean.csv)</li>
<li>[HS 2014](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_2014_clean.csv)</li>
<li>[HS 2013](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_2013_clean.csv)</li>
<li>[HS 2012](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_2012_clean.csv)</li>
<li>[HS 2011](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_2011_clean.csv)</li>
<li>[HS 2010](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_2010_clean.csv)</li>
<li>[HS 2009](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_2009_clean.csv)</li>
<li>[HS 2008](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_2008_clean.csv)</li>
<li>[HS 2007](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_2007_clean.csv)</li>
<li>[HS 2006](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_2006_clean.csv)</li>
<li>[HS 2005](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_2005_clean.csv)</li>
<li>[HS 2004](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_2004_clean.csv)</li>
<li>[HS 2003](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_2003_clean.csv)</li>
<li>[HS 2002](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_2002_clean.csv)</li>
<li>[HS 2001](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_2001_clean.csv)</li>
<li>[HS 2000](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_2000_clean.csv)</li>
<li>[HS 1999](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_1999_clean.csv)</li>
<li>[HS 1998](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_1998_clean.csv)</li>
<li>[HS 1997](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_1997_clean.csv)</li>
<li>[HS 1996](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_1996_clean.csv)</li>
<li>[HS 1995](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_1995_clean.csv)</li>
</div>

#### RDS

<div id="threecolumns">
<li>[HS 2015](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_2015_clean.rds)</li>
<li>[HS 2014](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_2014_clean.rds)</li>
<li>[HS 2013](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_2013_clean.rds)</li>
<li>[HS 2012](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_2012_clean.rds)</li>
<li>[HS 2011](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_2011_clean.rds)</li>
<li>[HS 2010](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_2010_clean.rds)</li>
<li>[HS 2009](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_2009_clean.rds)</li>
<li>[HS 2008](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_2008_clean.rds)</li>
<li>[HS 2007](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_2007_clean.rds)</li>
<li>[HS 2006](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_2006_clean.rds)</li>
<li>[HS 2005](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_2005_clean.rds)</li>
<li>[HS 2004](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_2004_clean.rds)</li>
<li>[HS 2003](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_2003_clean.rds)</li>
<li>[HS 2002](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_2002_clean.rds)</li>
<li>[HS 2001](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_2001_clean.rds)</li>
<li>[HS 2000](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_2000_clean.rds)</li>
<li>[HS 1999](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_1999_clean.rds)</li>
<li>[HS 1998](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_1998_clean.rds)</li>
<li>[HS 1997](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_1997_clean.rds)</li>
<li>[HS 1996](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_1996_clean.rds)</li>
<li>[HS 1995](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/hs92_1995_clean.rds)</li>
</div>

<div id="clean_data_un_comtrade_sitc_rev2">
### SITC (rev.2) clean data

#### CSV

<div id="threecolumns">
<li>[SITC rev.2 2015](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_2015_clean.csv)</li>
<li>[SITC rev.2 2014](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_2014_clean.csv)</li>
<li>[SITC rev.2 2013](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_2013_clean.csv)</li>
<li>[SITC rev.2 2012](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_2012_clean.csv)</li>
<li>[SITC rev.2 2011](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_2011_clean.csv)</li>
<li>[SITC rev.2 2010](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_2010_clean.csv)</li>
<li>[SITC rev.2 2009](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_2009_clean.csv)</li>
<li>[SITC rev.2 2008](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_2008_clean.csv)</li>
<li>[SITC rev.2 2007](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_2007_clean.csv)</li>
<li>[SITC rev.2 2006](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_2006_clean.csv)</li>
<li>[SITC rev.2 2005](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_2005_clean.csv)</li>
<li>[SITC rev.2 2004](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_2004_clean.csv)</li>
<li>[SITC rev.2 2003](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_2003_clean.csv)</li>
<li>[SITC rev.2 2002](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_2002_clean.csv)</li>
<li>[SITC rev.2 2001](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_2001_clean.csv)</li>
<li>[SITC rev.2 2000](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_2000_clean.csv)</li>
<li>[SITC rev.2 1999](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1999_clean.csv)</li>
<li>[SITC rev.2 1998](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1998_clean.csv)</li>
<li>[SITC rev.2 1997](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1997_clean.csv)</li>
<li>[SITC rev.2 1996](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1996_clean.csv)</li>
<li>[SITC rev.2 1995](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1995_clean.csv)</li>
<li>[SITC rev.2 1994](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1994_clean.csv)</li>
<li>[SITC rev.2 1993](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1993_clean.csv)</li>
<li>[SITC rev.2 1992](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1992_clean.csv)</li>
<li>[SITC rev.2 1991](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1991_clean.csv)</li>
<li>[SITC rev.2 1990](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1990_clean.csv)</li>
<li>[SITC rev.2 1989](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1989_clean.csv)</li>
<li>[SITC rev.2 1988](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1988_clean.csv)</li>
<li>[SITC rev.2 1987](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1987_clean.csv)</li>
<li>[SITC rev.2 1986](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1986_clean.csv)</li>
<li>[SITC rev.2 1985](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1985_clean.csv)</li>
<li>[SITC rev.2 1984](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1984_clean.csv)</li>
<li>[SITC rev.2 1983](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1983_clean.csv)</li>
<li>[SITC rev.2 1982](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1982_clean.csv)</li>
<li>[SITC rev.2 1981](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1981_clean.csv)</li>
<li>[SITC rev.2 1980](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1980_clean.csv)</li>
<li>[SITC rev.2 1979](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1979_clean.csv)</li>
<li>[SITC rev.2 1978](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1978_clean.csv)</li>
<li>[SITC rev.2 1977](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1977_clean.csv)</li>
<li>[SITC rev.2 1976](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1976_clean.csv)</li>
</div>

#### RDS

<div id="threecolumns">
<li>[SITC rev.2 2015](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_2015_clean.rds)</li>
<li>[SITC rev.2 2014](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_2014_clean.rds)</li>
<li>[SITC rev.2 2013](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_2013_clean.rds)</li>
<li>[SITC rev.2 2012](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_2012_clean.rds)</li>
<li>[SITC rev.2 2011](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_2011_clean.rds)</li>
<li>[SITC rev.2 2010](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_2010_clean.rds)</li>
<li>[SITC rev.2 2009](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_2009_clean.rds)</li>
<li>[SITC rev.2 2008](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_2008_clean.rds)</li>
<li>[SITC rev.2 2007](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_2007_clean.rds)</li>
<li>[SITC rev.2 2006](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_2006_clean.rds)</li>
<li>[SITC rev.2 2005](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_2005_clean.rds)</li>
<li>[SITC rev.2 2004](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_2004_clean.rds)</li>
<li>[SITC rev.2 2003](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_2003_clean.rds)</li>
<li>[SITC rev.2 2002](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_2002_clean.rds)</li>
<li>[SITC rev.2 2001](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_2001_clean.rds)</li>
<li>[SITC rev.2 2000](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_2000_clean.rds)</li>
<li>[SITC rev.2 1999](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1999_clean.rds)</li>
<li>[SITC rev.2 1998](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1998_clean.rds)</li>
<li>[SITC rev.2 1997](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1997_clean.rds)</li>
<li>[SITC rev.2 1996](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1996_clean.rds)</li>
<li>[SITC rev.2 1995](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1995_clean.rds)</li>
<li>[SITC rev.2 1994](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1994_clean.rds)</li>
<li>[SITC rev.2 1993](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1993_clean.rds)</li>
<li>[SITC rev.2 1992](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1992_clean.rds)</li>
<li>[SITC rev.2 1991](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1991_clean.rds)</li>
<li>[SITC rev.2 1990](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1990_clean.rds)</li>
<li>[SITC rev.2 1989](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1989_clean.rds)</li>
<li>[SITC rev.2 1988](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1988_clean.rds)</li>
<li>[SITC rev.2 1987](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1987_clean.rds)</li>
<li>[SITC rev.2 1986](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1986_clean.rds)</li>
<li>[SITC rev.2 1985](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1985_clean.rds)</li>
<li>[SITC rev.2 1984](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1984_clean.rds)</li>
<li>[SITC rev.2 1983](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1983_clean.rds)</li>
<li>[SITC rev.2 1982](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1982_clean.rds)</li>
<li>[SITC rev.2 1981](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1981_clean.rds)</li>
<li>[SITC rev.2 1980](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1980_clean.rds)</li>
<li>[SITC rev.2 1979](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1979_clean.rds)</li>
<li>[SITC rev.2 1978](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1978_clean.rds)</li>
<li>[SITC rev.2 1977](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1977_clean.rds)</li>
<li>[SITC rev.2 1976](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/sitc_rev2_1976_clean.rds)</li>
</div>

<div id="clean_data_un_comtrade_sitc_rev2">
### SITC (rev.1) clean data

#### CSV

<div id="threecolumns">
<li>[SITC rev.1 1975](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev1_clean/sitc_rev1_1975_clean.csv)</li>
<li>[SITC rev.1 1974](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev1_clean/sitc_rev1_1974_clean.csv)</li>
<li>[SITC rev.1 1973](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev1_clean/sitc_rev1_1973_clean.csv)</li>
<li>[SITC rev.1 1972](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev1_clean/sitc_rev1_1972_clean.csv)</li>
<li>[SITC rev.1 1971](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev1_clean/sitc_rev1_1971_clean.csv)</li>
<li>[SITC rev.1 1970](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev1_clean/sitc_rev1_1970_clean.csv)</li>
<li>[SITC rev.1 1969](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev1_clean/sitc_rev1_1969_clean.csv)</li>
<li>[SITC rev.1 1968](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev1_clean/sitc_rev1_1968_clean.csv)</li>
<li>[SITC rev.1 1967](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev1_clean/sitc_rev1_1967_clean.csv)</li>
<li>[SITC rev.1 1966](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev1_clean/sitc_rev1_1966_clean.csv)</li>
<li>[SITC rev.1 1965](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev1_clean/sitc_rev1_1965_clean.csv)</li>
<li>[SITC rev.1 1964](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev1_clean/sitc_rev1_1964_clean.csv)</li>
<li>[SITC rev.1 1963](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev1_clean/sitc_rev1_1963_clean.csv)</li>
<li>[SITC rev.1 1962](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev1_clean/sitc_rev1_1962_clean.csv)</li>
</div>

#### RDS

<div id="threecolumns">
<li>[SITC rev.1 1975](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev1_clean/sitc_rev1_1975_clean.rds)</li>
<li>[SITC rev.1 1974](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev1_clean/sitc_rev1_1974_clean.rds)</li>
<li>[SITC rev.1 1973](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev1_clean/sitc_rev1_1973_clean.rds)</li>
<li>[SITC rev.1 1972](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev1_clean/sitc_rev1_1972_clean.rds)</li>
<li>[SITC rev.1 1971](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev1_clean/sitc_rev1_1971_clean.rds)</li>
<li>[SITC rev.1 1970](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev1_clean/sitc_rev1_1970_clean.rds)</li>
<li>[SITC rev.1 1969](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev1_clean/sitc_rev1_1969_clean.rds)</li>
<li>[SITC rev.1 1968](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev1_clean/sitc_rev1_1968_clean.rds)</li>
<li>[SITC rev.1 1967](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev1_clean/sitc_rev1_1967_clean.rds)</li>
<li>[SITC rev.1 1966](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev1_clean/sitc_rev1_1966_clean.rds)</li>
<li>[SITC rev.1 1965](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev1_clean/sitc_rev1_1965_clean.rds)</li>
<li>[SITC rev.1 1964](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev1_clean/sitc_rev1_1964_clean.rds)</li>
<li>[SITC rev.1 1963](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev1_clean/sitc_rev1_1963_clean.rds)</li>
<li>[SITC rev.1 1962](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev1_clean/sitc_rev1_1962_clean.rds)</li>
</div>



<div id="raw_data">
# Raw data

<div id="raw_data_un_comtrade">
## UN COMTRADE

We do provide a copy of that sources on this page. There is no difference between our copies and the files stored at UN COMTRADE server. However, if you decide to download from UN COMTRADE there are some downloading restrictions such as downloading speed and number of files per hour so that we had unrestricted access by accesing it throughout [MIT Libraries](https://libraries.mit.edu/).

### Links to the sources

Here are the links to the original sources.

* [HS92 links to the original sources](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_links.xlsx)
* [SITC rev.2 links to the original sources](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_links.xlsx)
* [SITC rev.1 links to the original sources](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev1/sitc_rev1_links.xlsx)

<div id="raw_data_un_comtrade_hs92">
### HS92 raw data

#### ZIP (CSV format)

<div id="threecolumns">
<li>[HS92 2015](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_2015_csv.zip)</li>
<li>[HS92 2014](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_2014_csv.zip)</li>
<li>[HS92 2013](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_2013_csv.zip)</li>
<li>[HS92 2012](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_2012_csv.zip)</li>
<li>[HS92 2011](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_2011_csv.zip)</li>
<li>[HS92 2010](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_2010_csv.zip)</li>
<li>[HS92 2009](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_2009_csv.zip)</li>
<li>[HS92 2008](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_2008_csv.zip)</li>
<li>[HS92 2007](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_2007_csv.zip)</li>
<li>[HS92 2006](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_2006_csv.zip)</li>
<li>[HS92 2005](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_2005_csv.zip)</li>
<li>[HS92 2004](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_2004_csv.zip)</li>
<li>[HS92 2003](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_2003_csv.zip)</li>
<li>[HS92 2002](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_2002_csv.zip)</li>
<li>[HS92 2001](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_2001_csv.zip)</li>
<li>[HS92 2000](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_2000_csv.zip)</li>
<li>[HS92 1999](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1999_csv.zip)</li>
<li>[HS92 1998](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1998_csv.zip)</li>
<li>[HS92 1997](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1997_csv.zip)</li>
<li>[HS92 1996](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1996_csv.zip)</li>
<li>[HS92 1995](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1995_csv.zip)</li>
<li>[HS92 1994](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1994_csv.zip)</li>
<li>[HS92 1993](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1993_csv.zip)</li>
<li>[HS92 1992](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1992_csv.zip)</li>
<li>[HS92 1991](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1991_csv.zip)</li>
<li>[HS92 1990](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1990_csv.zip)</li>
<li>[HS92 1989](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1989_csv.zip)</li>
<li>[HS92 1988](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1988_csv.zip)</li>
<li>[HS92 1987](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1987_csv.zip)</li>
<li>[HS92 1986](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1986_csv.zip)</li>
<li>[HS92 1985](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1985_csv.zip)</li>
<li>[HS92 1984](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1984_csv.zip)</li>
<li>[HS92 1983](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1983_csv.zip)</li>
<li>[HS92 1982](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1982_csv.zip)</li>
<li>[HS92 1981](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1981_csv.zip)</li>
<li>[HS92 1980](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1980_csv.zip)</li>
<li>[HS92 1979](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1979_csv.zip)</li>
<li>[HS92 1978](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1978_csv.zip)</li>
<li>[HS92 1977](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1977_csv.zip)</li>
<li>[HS92 1976](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1976_csv.zip)</li>
</div>

#### RDS

<div id="threecolumns">
<li>[HS92 2015](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_2015.rds)</li>
<li>[HS92 2014](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_2014.rds)</li>
<li>[HS92 2013](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_2013.rds)</li>
<li>[HS92 2012](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_2012.rds)</li>
<li>[HS92 2011](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_2011.rds)</li>
<li>[HS92 2010](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_2010.rds)</li>
<li>[HS92 2009](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_2009.rds)</li>
<li>[HS92 2008](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_2008.rds)</li>
<li>[HS92 2007](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_2007.rds)</li>
<li>[HS92 2006](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_2006.rds)</li>
<li>[HS92 2005](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_2005.rds)</li>
<li>[HS92 2004](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_2004.rds)</li>
<li>[HS92 2003](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_2003.rds)</li>
<li>[HS92 2002](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_2002.rds)</li>
<li>[HS92 2001](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_2001.rds)</li>
<li>[HS92 2000](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_2000.rds)</li>
<li>[HS92 1999](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1999.rds)</li>
<li>[HS92 1998](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1998.rds)</li>
<li>[HS92 1997](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1997.rds)</li>
<li>[HS92 1996](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1996.rds)</li>
<li>[HS92 1995](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1995.rds)</li>
<li>[HS92 1994](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1994.rds)</li>
<li>[HS92 1993](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1993.rds)</li>
<li>[HS92 1992](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1992.rds)</li>
<li>[HS92 1991](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1991.rds)</li>
<li>[HS92 1990](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1990.rds)</li>
<li>[HS92 1989](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1989.rds)</li>
<li>[HS92 1988](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1988.rds)</li>
<li>[HS92 1987](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1987.rds)</li>
<li>[HS92 1986](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1986.rds)</li>
<li>[HS92 1985](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1985.rds)</li>
<li>[HS92 1984](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1984.rds)</li>
<li>[HS92 1983](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1983.rds)</li>
<li>[HS92 1982](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1982.rds)</li>
<li>[HS92 1981](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1981.rds)</li>
<li>[HS92 1980](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1980.rds)</li>
<li>[HS92 1979](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1979.rds)</li>
<li>[HS92 1978](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1978.rds)</li>
<li>[HS92 1977](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1977.rds)</li>
<li>[HS92 1976](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/hs92_1976.rds)</li>
</div>

<div id="raw_data_un_comtrade_sitc_rev2">
### SITC rev.2 raw data

#### ZIP (CSV format)

<div id="threecolumns">
<li>[SITC rev.2 2015](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_2015_csv.zip)</li>
<li>[SITC rev.2 2014](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_2014_csv.zip)</li>
<li>[SITC rev.2 2013](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_2013_csv.zip)</li>
<li>[SITC rev.2 2012](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_2012_csv.zip)</li>
<li>[SITC rev.2 2011](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_2011_csv.zip)</li>
<li>[SITC rev.2 2010](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_2010_csv.zip)</li>
<li>[SITC rev.2 2009](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_2009_csv.zip)</li>
<li>[SITC rev.2 2008](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_2008_csv.zip)</li>
<li>[SITC rev.2 2007](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_2007_csv.zip)</li>
<li>[SITC rev.2 2006](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_2006_csv.zip)</li>
<li>[SITC rev.2 2005](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_2005_csv.zip)</li>
<li>[SITC rev.2 2004](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_2004_csv.zip)</li>
<li>[SITC rev.2 2003](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_2003_csv.zip)</li>
<li>[SITC rev.2 2002](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_2002_csv.zip)</li>
<li>[SITC rev.2 2001](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_2001_csv.zip)</li>
<li>[SITC rev.2 2000](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_2000_csv.zip)</li>
<li>[SITC rev.2 1999](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1999_csv.zip)</li>
<li>[SITC rev.2 1998](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1998_csv.zip)</li>
<li>[SITC rev.2 1997](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1997_csv.zip)</li>
<li>[SITC rev.2 1996](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1996_csv.zip)</li>
<li>[SITC rev.2 1995](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1995_csv.zip)</li>
<li>[SITC rev.2 1994](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1994_csv.zip)</li>
<li>[SITC rev.2 1993](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1993_csv.zip)</li>
<li>[SITC rev.2 1992](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1992_csv.zip)</li>
<li>[SITC rev.2 1991](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1991_csv.zip)</li>
<li>[SITC rev.2 1990](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1990_csv.zip)</li>
<li>[SITC rev.2 1989](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1989_csv.zip)</li>
<li>[SITC rev.2 1988](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1988_csv.zip)</li>
<li>[SITC rev.2 1987](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1987_csv.zip)</li>
<li>[SITC rev.2 1986](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1986_csv.zip)</li>
<li>[SITC rev.2 1985](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1985_csv.zip)</li>
<li>[SITC rev.2 1984](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1984_csv.zip)</li>
<li>[SITC rev.2 1983](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1983_csv.zip)</li>
<li>[SITC rev.2 1982](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1982_csv.zip)</li>
<li>[SITC rev.2 1981](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1981_csv.zip)</li>
<li>[SITC rev.2 1980](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1980_csv.zip)</li>
<li>[SITC rev.2 1979](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1979_csv.zip)</li>
<li>[SITC rev.2 1978](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1978_csv.zip)</li>
<li>[SITC rev.2 1977](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1977_csv.zip)</li>
<li>[SITC rev.2 1976](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1976_csv.zip)</li>
</div>

#### RDS

<div id="threecolumns">
  <li>[SITC rev.2 2015](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_2015.rds)</li>
  <li>[SITC rev.2 2014](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_2014.rds)</li>
  <li>[SITC rev.2 2013](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_2013.rds)</li>
  <li>[SITC rev.2 2012](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_2012.rds)</li>
  <li>[SITC rev.2 2011](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_2011.rds)</li>
  <li>[SITC rev.2 2010](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_2010.rds)</li>
  <li>[SITC rev.2 2009](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_2009.rds)</li>
  <li>[SITC rev.2 2008](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_2008.rds)</li>
  <li>[SITC rev.2 2007](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_2007.rds)</li>
  <li>[SITC rev.2 2006](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_2006.rds)</li>
  <li>[SITC rev.2 2005](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_2005.rds)</li>
  <li>[SITC rev.2 2004](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_2004.rds)</li>
  <li>[SITC rev.2 2003](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_2003.rds)</li>
  <li>[SITC rev.2 2002](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_2002.rds)</li>
  <li>[SITC rev.2 2001](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_2001.rds)</li>
  <li>[SITC rev.2 2000](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_2000.rds)</li>
  <li>[SITC rev.2 1999](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1999.rds)</li>
  <li>[SITC rev.2 1998](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1998.rds)</li>
  <li>[SITC rev.2 1997](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1997.rds)</li>
  <li>[SITC rev.2 1996](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1996.rds)</li>
  <li>[SITC rev.2 1995](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1995.rds)</li>
  <li>[SITC rev.2 1994](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1994.rds)</li>
  <li>[SITC rev.2 1993](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1993.rds)</li>
  <li>[SITC rev.2 1992](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1992.rds)</li>
  <li>[SITC rev.2 1991](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1991.rds)</li>
  <li>[SITC rev.2 1990](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1990.rds)</li>
  <li>[SITC rev.2 1989](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1989.rds)</li>
  <li>[SITC rev.2 1988](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1988.rds)</li>
  <li>[SITC rev.2 1987](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1987.rds)</li>
  <li>[SITC rev.2 1986](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1986.rds)</li>
  <li>[SITC rev.2 1985](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1985.rds)</li>
  <li>[SITC rev.2 1984](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1984.rds)</li>
  <li>[SITC rev.2 1983](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1983.rds)</li>
  <li>[SITC rev.2 1982](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1982.rds)</li>
  <li>[SITC rev.2 1981](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1981.rds)</li>
  <li>[SITC rev.2 1980](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1980.rds)</li>
  <li>[SITC rev.2 1979](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1979.rds)</li>
  <li>[SITC rev.2 1978](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1978.rds)</li>
  <li>[SITC rev.2 1977](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1977.rds)</li>
  <li>[SITC rev.2 1976](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/sitc_rev2_1976.rds)</li>
</div>

<div id="raw_data_un_comtrade_sitc_rev1">
### SITC rev.1 raw data

#### ZIP (CSV format)

<div id="threecolumns">
<li>[SITC rev.1 1975](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev1/sitc_rev1_1975_csv.zip)</li>
<li>[SITC rev.1 1974](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev1/sitc_rev1_1974_csv.zip)</li>
<li>[SITC rev.1 1973](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev1/sitc_rev1_1973_csv.zip)</li>
<li>[SITC rev.1 1972](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev1/sitc_rev1_1972_csv.zip)</li>
<li>[SITC rev.1 1971](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev1/sitc_rev1_1971_csv.zip)</li>
<li>[SITC rev.1 1970](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev1/sitc_rev1_1970_csv.zip)</li>
<li>[SITC rev.1 1969](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev1/sitc_rev1_1969_csv.zip)</li>
<li>[SITC rev.1 1968](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev1/sitc_rev1_1968_csv.zip)</li>
<li>[SITC rev.1 1967](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev1/sitc_rev1_1967_csv.zip)</li>
<li>[SITC rev.1 1966](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev1/sitc_rev1_1966_csv.zip)</li>
<li>[SITC rev.1 1965](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev1/sitc_rev1_1965_csv.zip)</li>
<li>[SITC rev.1 1964](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev1/sitc_rev1_1964_csv.zip)</li>
<li>[SITC rev.1 1963](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev1/sitc_rev1_1963_csv.zip)</li>
<li>[SITC rev.1 1962](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev1/sitc_rev1_1962_csv.zip)</li>
</div>

#### RDS

<div id="threecolumns">
<li>[SITC rev.1 1975](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev1/sitc_rev1_1975.rds)</li>
<li>[SITC rev.1 1974](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev1/sitc_rev1_1974.rds)</li>
<li>[SITC rev.1 1973](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev1/sitc_rev1_1973.rds)</li>
<li>[SITC rev.1 1972](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev1/sitc_rev1_1972.rds)</li>
<li>[SITC rev.1 1971](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev1/sitc_rev1_1971.rds)</li>
<li>[SITC rev.1 1970](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev1/sitc_rev1_1970.rds)</li>
<li>[SITC rev.1 1969](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev1/sitc_rev1_1969.rds)</li>
<li>[SITC rev.1 1968](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev1/sitc_rev1_1968.rds)</li>
<li>[SITC rev.1 1967](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev1/sitc_rev1_1967.rds)</li>
<li>[SITC rev.1 1966](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev1/sitc_rev1_1966.rds)</li>
<li>[SITC rev.1 1965](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev1/sitc_rev1_1965.rds)</li>
<li>[SITC rev.1 1964](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev1/sitc_rev1_1964.rds)</li>
<li>[SITC rev.1 1963](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev1/sitc_rev1_1963.rds)</li>
<li>[SITC rev.1 1962](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev1/sitc_rev1_1962.rds)</li>
</div>

<div id="raw_data_cepii">
## CEPII

<div id="raw_data_cepii_geo">
### Geo raw data

* [Geo data (XLS)](http://pacha.datawheel.us/oec/datasets/cepii_data/geo/geo_cepii.xls) 

* [Geo data (RData)](http://pacha.datawheel.us/oec/datasets/cepii_data/geo/geo_data.RData) 

<div id="raw_data_cepii_gravity">
### Gravity raw data

* [Gravity data (RData)](http://pacha.datawheel.us/oec/datasets/cepii_data/gravity/gravity_data.RData) 
* [Gravity data (DTA)](http://pacha.datawheel.us/oec/datasets/cepii_data/gravity/gravdata_cepii.zip)



<div id="documentation">
# Documentation

<div id="documentation_cepii">
## CEPII

* [Gravity documentation (DOC)](http://pacha.datawheel.us/oec/datasets/cepii_data/gravity/gravdata_doc.doc)



<div id="scripts">
# Scripts

If you want to run this scripts in your server create an RStudio project put these scripts in your project folder:

* [Set up everything](http://pacha.datawheel.us/oec/datasets/0_set_up_everything.R)
* [Create folders](http://pacha.datawheel.us/oec/datasets/1_create_folders.R)
* [Download scripts](http://pacha.datawheel.us/oec/datasets/2_download_scripts.R)

Then run `0_set_up_everything.R`, the folders structure will be replicated and the scripts will be downloaded to their respective folders. After that you'll be ready to run *all* of the scripts of this projects to convert and clean the data yourself.

<div id="scripts_un_comtrade">
## UN COMTRADE

<div id="scripts_un_comtrade_hs92">
### HS92

* [HS92 raw data: Convert to RDS](http://pacha.datawheel.us/oec/datasets/comtrade_data/hs92/1_convert_to_rds.R)
* [HS92 clean data: Verify and re-order data](http://pacha.datawheel.us/oec/datasets/pacha_files/hs92_clean/1_verify_imports_and_exports.R)

<div id="scripts_un_comtrade_sitc_rev2">
### SITC (rev. 2)
* [SITC (rev. 2) raw data: Convert to RDS](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev2/1_convert_to_rds.R)
* [SITC (rev. 2) clean data: Verify and re-order data](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev2_clean/1_verify_imports_and_exports.R)

<div id="scripts_un_comtrade_sitc_rev1">
### SITC (rev. 1)
* [SITC (rev. 1) raw data: Convert to RDS](http://pacha.datawheel.us/oec/datasets/comtrade_data/sitc_rev1/1_convert_to_rds.R)
* [SITC (rev. 1) clean data: Verify and re-order data](http://pacha.datawheel.us/oec/datasets/pacha_files/sitc_rev1_clean/1_verify_imports_and_exports.R)

<div id="scripts_cepii">
## CEPII

* [Geo raw data: Convert to R](http://pacha.datawheel.us/oec/datasets/cepii_data/geo/1_convert_excel.R) 

* [Gravity raw data: Convert to R](http://pacha.datawheel.us/oec/datasets/cepii_data/gravity/1_convert_stata.R)
