library(devtools)
library(roxygen2)
library(knitr)
document()
system("R CMD Rd2pdf ~/public_www/oec/r_package/")
file.rename("~/public_www/oec/r_package/r_package.pdf", "~/public_www/oec/r_package/oec.pdf")
file.remove("~/public_www/oec/examples/oec.pdf")
file.copy("~/public_www/oec/r_package/oec.pdf", "~/public_www/oec/examples/")
file.remove("~/public_www/oec/r_package/oec.pdf")
#check()
