setwd("~/oec/r_package")
library(devtools)
library(roxygen2)
library(knitr)
document()
system("R CMD Rd2pdf ~/oec/r_package/")
file.rename("~/oec/r_package/r_package.pdf", "~/oec/r_package/oec.pdf")
file.remove("~/oec/gh-pages/oec.pdf")
file.copy("~/oec/r_package/oec.pdf", "~/oec/gh-pages/")
file.remove("~/oec/r_package/oec.pdf")
file.remove("~/oec/gh-pages/README.md")
file.copy("~/oec/README.md", "~/oec/gh-pages/README.md")
#check()
